services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SqlServerPW!"
    ports:
    - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P SqlServerPW! -C -Q 'SELECT 1'"]
      interval: 10s
      retries: 3
      start_interval: 30s
    networks:
    - cashflow

  tools-runner:
    build:
     context: .
     dockerfile: src/Cashflow.ToolsRunner/Dockerfile
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
    - cashflow

  cashflow-api:
    build:
      context: .
      dockerfile: src/Cashflow.ApiServer/Dockerfile
    depends_on:
      tools-runner:
        condition: service_completed_successfully
    ports:
    - "5000:80"
    networks:
    - cashflow

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
    - "2181:2181"
    networks:
    - cashflow

  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
    - zookeeper
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
    - "9092:9092"
    networks:
    - cashflow
  
networks:
  cashflow:
    driver: bridge